DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS balance_events CASCADE;
DROP TABLE IF EXISTS budget_goals CASCADE;
DROP TABLE IF EXISTS expense_category CASCADE;
DROP TABLE IF EXISTS income_category CASCADE;
DROP TABLE IF EXISTS income_sources CASCADE;